### ISSUE TITLE
Multiple applications

### ISSUE THREAD

**Issue by Tall-Paul** [ProxiBlue/NewRelic#17]
Hi, 

I set up newrelic on my servers this morning and all seemed to be going well.  Then I installed your extension.

I now have 2 applications showing, both named exactly the same.  

The original application is now showing page load times massively below what it was showing before installing the extension, while the new application seems to be showing the difference.

original application:

![screen shot 2014-08-01 at 11 35 36](https://cloud.githubusercontent.com/assets/600126/3777817/d161e0ee-1967-11e4-84f6-186f04a09cdd.png)

new application:

![screen shot 2014-08-01 at 11 35 50](https://cloud.githubusercontent.com/assets/600126/3777820/da0bcc32-1967-11e4-995f-18da25903a24.png)

...what's the deal?

**Comment by dbashyal** [comment]
Thanks Lucas. That fixed the multiple application issue for me too :)
