### ISSUE TITLE
PHP Compatibility

### ISSUE THREAD

**Issue by barbazul** [ProxiBlue/NewRelic#22]
This is probably minor for most installs but I just run into this issue.

The module is listed as being compatible with Magento CE 1.4 which in turn is compatible with PHP 5.2

However there is a rewrite of Mage_Core_Exception that uses PHP 5.3 constructor by passing the $previous parameter.

I think the correct fix here would be to make a notice in the README notifying compatibility with PHP 5.3+ as I don't think its worth the trouble to compatibilize with PHP 5.2 as it is absolutely deprecated.

**Comment by ProxiBlue** [comment]
Hi, thanks for noting this, and I agree, no point in going backwards compatible. If someone want to do that, they can do a fork. Just no longer supported.

**Comment by ProxiBlue** [comment]
Readme updated accordingly
