### ISSUE TITLE
Renaming a few methods (layout related)

### ISSUE THREAD

**Issue by melvyn-sopacua** [ProxiBlue/NewRelic#23]
I'd like to contribute a piece that alters Mage_Core_Layout::createBlock('suppressed/blockargument') into Visible_Blockargument::createLayout() for transaction traces and was looking into New Relic API support. I think it can be done with a custom tracer, but was wondering if you guys had looked into this and if so can you share your insights?
If I use a custom tracer, it seems like I need to implement a lot more then just name change which could introduce errors, so I'm torn between requesting a feature with New Relic to support alternative names for method calls or go ahead and code a custom tracer. Maybe there is a third option I'm not seeing.

**Comment by ProxiBlue** [comment]
Hi, not 100% sure what you are trying to do, however, the https://github.com/yireo/Yireo_NewRelic module is more about using custom tracers, and debug information pushed to newrelic. Possible their module can help, or the question posted to them?

**Comment by melvyn-sopacua** [comment]
Maybe, I'll have a look. I discarded it because it mentions using Varien_Profiler, which defeats an important USP of New Relic: don't need profiler injections in the code to measure and list it.

The goal is not to do custom tracing, the goal is to make all the calls to create blocks mean something useful, so you can actually relate it to templates / blocks instead of deeply nested collection of generic calls.

I'll do my research and see where it fits best.
