### ISSUE TITLE
Named Transactions on Magento 1.5.1.0 show /index.php

### ISSUE THREAD

**Issue by geoffjukes** [ProxiBlue/NewRelic#27]
Hi,

Great extension. Thank you!

We used to run the Yireo extension, with the "named transactions" enabled. These showed in NewRelic as the request URI. 

After switching to your plugin, all of our named transactions show as /index.php (with the request URI in grey below it). This means makes it impossible to track key transactions. 

Is this a bug? Or an incompatibility with 1.5.1.0?

Many thanks,

Geoff

**Comment by ProxiBlue** [comment]
Hi.

There is an option in admin to enable named transactions.

Are you getting this issue with that enabled?

**Comment by geoffjukes** [comment]
Hi,

Yes, I have that option enabled. 

If I turn that option off, I stop getting transaction traces completely. 

Geoff

**Comment by ProxiBlue** [comment]
Must be an incompatibility in magento 1.5.

I will have to consuct some tests, however please note i am a bit busy on
paid for projects. May take a couple of weeks to look into.

**Comment by geoffjukes** [comment]
Ok, thank you.

I just checked, and I do get 2 "properly named" Transactions, both of which are from the NoRoute controller. 

I am going to investigate if something is hijacking the route controller in a way that breaks the extension.

**Comment by ProxiBlue** [comment]
Any further news on this?

**Comment by geoffjukes** [comment]
Hi,

No, no news. It is still naming everything '/index.php'.

We use per-application names in NewRelic, so the PHP agent has the name "Unknown PHP Application", Then this extension is set with the "real" application name.

I have noticed that some "properly named" transactions are appearing in the "Unknown PHP Application".

**Comment by ProxiBlue** [comment]
Closing as dated.
