### ISSUE TITLE
Mage/Newrelic/Model/Log/Exception.php. No such file or directory

### ISSUE THREAD

**Issue by eniuz** [ProxiBlue/NewRelic#29]
Warning: include(Mage/Newrelic/Model/Log/Exception.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory  in /var/www/html/lib/Varien/Autoload.php on line 92

Warning: include() [<a href='function.include'>function.include</a>]: Failed opening 'Mage/Newrelic/Model/Log/Exception.php' for inclusion (include_path='/var/www/html/app/code/local:/var/www/html/app/code/community:/var/www/html/app/code/core:/var/www/html/lib:.:/usr/share/pear:/usr/share/php')  in /var/www/html/lib/Varien/Autoload.php on line 92

**Comment by ProxiBlue** [comment]
Did you recently update the extension?

The namespace is incorrect : Newrelic (old) should be 'ProxiBlue_NewRelic' (new) namespace

**Comment by eniuz** [comment]
You're right is outdated. Cheers
