### ISSUE TITLE
Template for dashboard needs renaming

### ISSUE THREAD

**Issue by maderlock** [ProxiBlue/NewRelic#30]
In changing the namespace, Block/Adminhtml/Dashboard/Tab/Newrelic.php has had the path to the dashboard tab template changed to proxiblue_newrelic.phtml.phtml. However, the template has not been renamed. This causes a warning, which when developing with strict warnings turned on means that the admin panel does not work at all. Easy fix, though :)

**Comment by ProxiBlue** [comment]
Hi,

Thanks for this. Been meaning to fix this, just never seemed to get the time.

Do you mind renaming the file in modman as well, so it can all go in one PR

https://github.com/ProxiBlue/NewRelic/blob/master/modman
