### ISSUE TITLE
newrelic_base_url is not defined

### ISSUE THREAD

**Issue by alexjamesbrown** [ProxiBlue/NewRelic#34]
Getting this js error when I fill in my api key and press:

![image](https://cloud.githubusercontent.com/assets/437743/15399120/55038fb6-1dde-11e6-840d-11e0d3dced38.png)

Similarly, if I manually fill in the details and press Fetch Application Names
Same js error

**Comment by ProxiBlue** [comment]
Hi,

The variable is defined in this file: 

https://github.com/ProxiBlue/NewRelic/blob/master/app/design/adminhtml/default/default/template/proxiblue_newrelic/init_js.phtml

Does this file exist in your install?
How did you install? github/composer/zip/magento connect 

If the file does not exist, grabe the one from github in the given link and place it.

**Comment by ProxiBlue** [comment]
If the noted file exist, then check if the layout file exist:

https://github.com/ProxiBlue/NewRelic/blob/master/app/design/adminhtml/default/default/layout/proxiblue_newrelic.xml

If not, then again, pull the one from github.

**Comment by alexjamesbrown** [comment]
Installed using zip into our working copy.
we use deployBot to deploy via git

yep, both files there on the live server in their expected location.

**Comment by alexjamesbrown** [comment]
ignore -

cleared cache (for the 3rd time)
seems to work - albeit says i got an invalid api key... but i'll look into that

**Comment by ProxiBlue** [comment]
Ok, this is a first time for this type of issue, will consider what can cause this, and send you any thoughts.

I would be interested if the variable code runs at all.
I would determine if the code noted actually runs, and if any definition of the variable is present in the DOM. Sounds to me like the block is not executed/rendered.

Do you use a custom admin theme?

**Comment by alexjamesbrown** [comment]
I see this in the DOM

    var newrelic_base_url = 'https://www.gardeningexpress.co.uk/';

But no matter what I put in, I just get 'invalid api key'

**Comment by ProxiBlue** [comment]
Ok. Ping me via support.proxiblue.com.
Link to this ticket in comment.

I need to have a look, so need access. The support ticket will be a private medium to continue this in.

I will only be able to look at this in about 2 weeks, as i am busy on a time critical task

**Comment by alexjamesbrown** [comment]
Ok, will catch up in 2 weeks, have used another extension for now, but can easily revert to this in a while
